// This file is auto-generated by scripts/generate-icon-registry.mjs
import type { ComponentType } from "react";

import AlarmIcon from "../assets/AlarmIcon";
import AlarmVariantOneIcon from "../assets/AlarmVariantOneIcon";
import AnchorLinkIcon from "../assets/AnchorLinkIcon";
import AppleIcon from "../assets/AppleIcon";
import ArrowDownIcon from "../assets/ArrowDownIcon";
import ArrowLeftIcon from "../assets/ArrowLeftIcon";
import ArrowRightIcon from "../assets/ArrowRightIcon";
import ArrowUpIcon from "../assets/ArrowUpIcon";
import BagIcon from "../assets/BagIcon";
import BagVariantOneIcon from "../assets/BagVariantOneIcon";
import BagVariantTwoIcon from "../assets/BagVariantTwoIcon";
import BellIcon from "../assets/BellIcon";
import BellSlashIcon from "../assets/BellSlashIcon";
import BellSlashVariantOneIcon from "../assets/BellSlashVariantOneIcon";
import BellVariantOneIcon from "../assets/BellVariantOneIcon";
import BellVariantTwoIcon from "../assets/BellVariantTwoIcon";
import BitbucketIcon from "../assets/BitbucketIcon";
import BitbucketVariantOneIcon from "../assets/BitbucketVariantOneIcon";
import BookmarkIcon from "../assets/BookmarkIcon";
import BraveIcon from "../assets/BraveIcon";
import BugIcon from "../assets/BugIcon";
import BugSlashIcon from "../assets/BugSlashIcon";
import CalendarIcon from "../assets/CalendarIcon";
import CalendarVariantOneIcon from "../assets/CalendarVariantOneIcon";
import CameraIcon from "../assets/CameraIcon";
import CameraSlashIcon from "../assets/CameraSlashIcon";
import CameraVariantOneIcon from "../assets/CameraVariantOneIcon";
import CameraVariantTwoIcon from "../assets/CameraVariantTwoIcon";
import CameraVariantThreeIcon from "../assets/CameraVariantThreeIcon";
import CameraVariantFourIcon from "../assets/CameraVariantFourIcon";
import CartIcon from "../assets/CartIcon";
import CartVariantOneIcon from "../assets/CartVariantOneIcon";
import CartVariantTwoIcon from "../assets/CartVariantTwoIcon";
import ChatIcon from "../assets/ChatIcon";
import ChatCheckIcon from "../assets/ChatCheckIcon";
import ChatCloseIcon from "../assets/ChatCloseIcon";
import ChatDotsHorizontalIcon from "../assets/ChatDotsHorizontalIcon";
import ChatExclamationIcon from "../assets/ChatExclamationIcon";
import ChatInfoIcon from "../assets/ChatInfoIcon";
import ChatQuestionIcon from "../assets/ChatQuestionIcon";
import CheckIcon from "../assets/CheckIcon";
import CheckCircleIcon from "../assets/CheckCircleIcon";
import ChevronDownIcon from "../assets/ChevronDownIcon";
import ChevronLeftIcon from "../assets/ChevronLeftIcon";
import ChevronRightIcon from "../assets/ChevronRightIcon";
import ChevronUpIcon from "../assets/ChevronUpIcon";
import ChromeIcon from "../assets/ChromeIcon";
import ClockIcon from "../assets/ClockIcon";
import ClockVariantOneIcon from "../assets/ClockVariantOneIcon";
import ClockVariantTwoIcon from "../assets/ClockVariantTwoIcon";
import CloseIcon from "../assets/CloseIcon";
import CloudDownloadIcon from "../assets/CloudDownloadIcon";
import CloudDownloadVariantOneIcon from "../assets/CloudDownloadVariantOneIcon";
import CodeIcon from "../assets/CodeIcon";
import CodeVariantOneIcon from "../assets/CodeVariantOneIcon";
import CopyIcon from "../assets/CopyIcon";
import CopyVariantOneIcon from "../assets/CopyVariantOneIcon";
import DiscordIcon from "../assets/DiscordIcon";
import DiscordVariantOneIcon from "../assets/DiscordVariantOneIcon";
import DockerIcon from "../assets/DockerIcon";
import DocumentIcon from "../assets/DocumentIcon";
import DocumentVariantOneIcon from "../assets/DocumentVariantOneIcon";
import DocumentVariantTwoIcon from "../assets/DocumentVariantTwoIcon";
import DotsHorizontalIcon from "../assets/DotsHorizontalIcon";
import DotsVerticalIcon from "../assets/DotsVerticalIcon";
import DoubleChevronDownIcon from "../assets/DoubleChevronDownIcon";
import DoubleChevronLeftIcon from "../assets/DoubleChevronLeftIcon";
import DoubleChevronRightIcon from "../assets/DoubleChevronRightIcon";
import DoubleChevronUpIcon from "../assets/DoubleChevronUpIcon";
import DownloadIcon from "../assets/DownloadIcon";
import DownloadVariantOneIcon from "../assets/DownloadVariantOneIcon";
import DownloadVariantTwoIcon from "../assets/DownloadVariantTwoIcon";
import EditImageIcon from "../assets/EditImageIcon";
import ExclamationMarkIcon from "../assets/ExclamationMarkIcon";
import ExternalLinkIcon from "../assets/ExternalLinkIcon";
import EyeIcon from "../assets/EyeIcon";
import EyeClosedIcon from "../assets/EyeClosedIcon";
import EyeSlashIcon from "../assets/EyeSlashIcon";
import EyeSlashVariantOneIcon from "../assets/EyeSlashVariantOneIcon";
import EyeVariantOneIcon from "../assets/EyeVariantOneIcon";
import FacebookIcon from "../assets/FacebookIcon";
import FeedIcon from "../assets/FeedIcon";
import FilterIcon from "../assets/FilterIcon";
import FilterVariantOneIcon from "../assets/FilterVariantOneIcon";
import FirefoxIcon from "../assets/FirefoxIcon";
import FolderIcon from "../assets/FolderIcon";
import FolderVariantOneIcon from "../assets/FolderVariantOneIcon";
import FolderVariantTwoIcon from "../assets/FolderVariantTwoIcon";
import GitIcon from "../assets/GitIcon";
import GitBranchIcon from "../assets/GitBranchIcon";
import GitBranchVariantOneIcon from "../assets/GitBranchVariantOneIcon";
import GitCommitIcon from "../assets/GitCommitIcon";
import GitCommitVariantOneIcon from "../assets/GitCommitVariantOneIcon";
import GitMergeIcon from "../assets/GitMergeIcon";
import GitMergeVariantOneIcon from "../assets/GitMergeVariantOneIcon";
import GitPullRequestIcon from "../assets/GitPullRequestIcon";
import GitPullRequestVariantOneIcon from "../assets/GitPullRequestVariantOneIcon";
import GitVariantOneIcon from "../assets/GitVariantOneIcon";
import GithubIcon from "../assets/GithubIcon";
import GitlabIcon from "../assets/GitlabIcon";
import GitlabVariantOneIcon from "../assets/GitlabVariantOneIcon";
import GoogleIcon from "../assets/GoogleIcon";
import GoogleDriveIcon from "../assets/GoogleDriveIcon";
import GoogleMeetIcon from "../assets/GoogleMeetIcon";
import GoogleVariantOneIcon from "../assets/GoogleVariantOneIcon";
import HalfHeartIcon from "../assets/HalfHeartIcon";
import HalfHeartFilledIcon from "../assets/HalfHeartFilledIcon";
import HalfStarIcon from "../assets/HalfStarIcon";
import HalfStarFilledIcon from "../assets/HalfStarFilledIcon";
import HeartIcon from "../assets/HeartIcon";
import HeartFilledIcon from "../assets/HeartFilledIcon";
import HomeIcon from "../assets/HomeIcon";
import HomeVariantOneIcon from "../assets/HomeVariantOneIcon";
import ImageIcon from "../assets/ImageIcon";
import ImageCheckIcon from "../assets/ImageCheckIcon";
import ImageCloseIcon from "../assets/ImageCloseIcon";
import ImageMinusIcon from "../assets/ImageMinusIcon";
import ImagePlusIcon from "../assets/ImagePlusIcon";
import ImageVariantOneIcon from "../assets/ImageVariantOneIcon";
import InfoIcon from "../assets/InfoIcon";
import InstagramIcon from "../assets/InstagramIcon";
import InstagramOldIcon from "../assets/InstagramOldIcon";
import InternetExplorerIcon from "../assets/InternetExplorerIcon";
import InternetGlobeIcon from "../assets/InternetGlobeIcon";
import InternetGlobeVariantOneIcon from "../assets/InternetGlobeVariantOneIcon";
import LinkedinIcon from "../assets/LinkedinIcon";
import LinkedinVariantOneIcon from "../assets/LinkedinVariantOneIcon";
import LocationIcon from "../assets/LocationIcon";
import LocationVariantOneIcon from "../assets/LocationVariantOneIcon";
import MailIcon from "../assets/MailIcon";
import MailOpenIcon from "../assets/MailOpenIcon";
import MailVariantOneIcon from "../assets/MailVariantOneIcon";
import MenuIcon from "../assets/MenuIcon";
import MessengerIcon from "../assets/MessengerIcon";
import MetaIcon from "../assets/MetaIcon";
import MicrosoftIcon from "../assets/MicrosoftIcon";
import MicrosoftEdgeIcon from "../assets/MicrosoftEdgeIcon";
import MicrosoftTeamsIcon from "../assets/MicrosoftTeamsIcon";
import MinusIcon from "../assets/MinusIcon";
import MinusCircleIcon from "../assets/MinusCircleIcon";
import MobilePhoneIcon from "../assets/MobilePhoneIcon";
import MobilePhoneVariantOneIcon from "../assets/MobilePhoneVariantOneIcon";
import MoonIcon from "../assets/MoonIcon";
import MoonInTheSeaIcon from "../assets/MoonInTheSeaIcon";
import MoonVariantOneIcon from "../assets/MoonVariantOneIcon";
import NpmIcon from "../assets/NpmIcon";
import NpmVariantOneIcon from "../assets/NpmVariantOneIcon";
import OperaIcon from "../assets/OperaIcon";
import PauseIcon from "../assets/PauseIcon";
import PencilIcon from "../assets/PencilIcon";
import PencilVariantOneIcon from "../assets/PencilVariantOneIcon";
import PencilVariantTwoIcon from "../assets/PencilVariantTwoIcon";
import PhoneIcon from "../assets/PhoneIcon";
import PhoneVariantOneIcon from "../assets/PhoneVariantOneIcon";
import PinterestIcon from "../assets/PinterestIcon";
import PinterestVariantOneIcon from "../assets/PinterestVariantOneIcon";
import PlayIcon from "../assets/PlayIcon";
import PlayPauseIcon from "../assets/PlayPauseIcon";
import PlusIcon from "../assets/PlusLargeIcon";
import PlusCircleIcon from "../assets/PlusCircleIcon";
import PlusMinusIcon from "../assets/PlusMinusIcon";
import ProfileIcon from "../assets/ProfileIcon";
import ProfileVariantOneIcon from "../assets/ProfileVariantOneIcon";
import QuestionMarkIcon from "../assets/QuestionMarkIcon";
import RedditIcon from "../assets/RedditIcon";
import RefreshIcon from "../assets/RefreshIcon";
import RefreshVariantOneIcon from "../assets/RefreshVariantOneIcon";
import SafariIcon from "../assets/SafariIcon";
import SaveIcon from "../assets/SaveIcon";
import SaveVariantOneIcon from "../assets/SaveVariantOneIcon";
import SaveVariantTwoIcon from "../assets/SaveVariantTwoIcon";
import SearchIcon from "../assets/SearchIcon";
import SendIcon from "../assets/SendIcon";
import SendVariantOneIcon from "../assets/SendVariantOneIcon";
import SendVariantTwoIcon from "../assets/SendVariantTwoIcon";
import SendVariantThreeIcon from "../assets/SendVariantThreeIcon";
import SendVariantFourIcon from "../assets/SendVariantFourIcon";
import SettingsIcon from "../assets/SettingsIcon";
import SettingsVariantOneIcon from "../assets/SettingsVariantOneIcon";
import SignalIcon from "../assets/SignalIcon";
import SkypeIcon from "../assets/SkypeIcon";
import SlackIcon from "../assets/SlackIcon";
import SnapchatIcon from "../assets/SnapchatIcon";
import SnapchatVariantOneIcon from "../assets/SnapchatVariantOneIcon";
import StackoverflowIcon from "../assets/StackoverflowIcon";
import StarIcon from "../assets/StarIcon";
import StarFilledIcon from "../assets/StarFilledIcon";
import SunIcon from "../assets/SunIcon";
import SunInTheSeaIcon from "../assets/SunInTheSeaIcon";
import SunVariantOneIcon from "../assets/SunVariantOneIcon";
import TelegramIcon from "../assets/TelegramIcon";
import TelegramVariantOneIcon from "../assets/TelegramVariantOneIcon";
import TerminalIcon from "../assets/TerminalIcon";
import TerminalVariantOneIcon from "../assets/TerminalVariantOneIcon";
import TerminalVariantTwoIcon from "../assets/TerminalVariantTwoIcon";
import TiktokIcon from "../assets/TiktokIcon";
import TrashIcon from "../assets/TrashIcon";
import TrashVariantOneIcon from "../assets/TrashVariantOneIcon";
import TwitchIcon from "../assets/TwitchIcon";
import TwitterIcon from "../assets/TwitterIcon";
import UploadIcon from "../assets/UploadIcon";
import UploadVariantOneIcon from "../assets/UploadVariantOneIcon";
import UploadVariantTwoIcon from "../assets/UploadVariantTwoIcon";
import VercelIcon from "../assets/VercelIcon";
import VercelVariantOneIcon from "../assets/VercelVariantOneIcon";
import WarningCircleIcon from "../assets/WarningCircleIcon";
import WarningTriangleIcon from "../assets/WarningTriangleIcon";
import WhatsappIcon from "../assets/WhatsappIcon";
import WifiIcon from "../assets/WifiIcon";
import WifiExclamationIcon from "../assets/WifiExclamationIcon";
import WifiLowIcon from "../assets/WifiLowIcon";
import WifiMediumIcon from "../assets/WifiMediumIcon";
import WifiSlashIcon from "../assets/WifiSlashIcon";
import WifiVeryLowIcon from "../assets/WifiVeryLowIcon";
import WindowsIcon from "../assets/WindowsIcon";
import YoutubeIcon from "../assets/YoutubeIcon";
import YoutubeVariantOneIcon from "../assets/YoutubeVariantOneIcon";

import type { IconProps, Icons } from "../types/shared";

const iconRegistry: Record<Icons, ComponentType<IconProps>> = {
  "alarm": AlarmIcon,
  "alarm-variant-1": AlarmVariantOneIcon,
  "anchor-link": AnchorLinkIcon,
  "apple": AppleIcon,
  "arrow-down": ArrowDownIcon,
  "arrow-left": ArrowLeftIcon,
  "arrow-right": ArrowRightIcon,
  "arrow-up": ArrowUpIcon,
  "bag": BagIcon,
  "bag-variant-1": BagVariantOneIcon,
  "bag-variant-2": BagVariantTwoIcon,
  "bell": BellIcon,
  "bell-slash": BellSlashIcon,
  "bell-slash-variant-1": BellSlashVariantOneIcon,
  "bell-variant-1": BellVariantOneIcon,
  "bell-variant-2": BellVariantTwoIcon,
  "bitbucket": BitbucketIcon,
  "bitbucket-variant-1": BitbucketVariantOneIcon,
  "bookmark": BookmarkIcon,
  "brave": BraveIcon,
  "bug": BugIcon,
  "bug-slash": BugSlashIcon,
  "calendar": CalendarIcon,
  "calendar-variant-1": CalendarVariantOneIcon,
  "camera": CameraIcon,
  "camera-slash": CameraSlashIcon,
  "camera-variant-1": CameraVariantOneIcon,
  "camera-variant-2": CameraVariantTwoIcon,
  "camera-variant-3": CameraVariantThreeIcon,
  "camera-variant-4": CameraVariantFourIcon,
  "cart": CartIcon,
  "cart-variant-1": CartVariantOneIcon,
  "cart-variant-2": CartVariantTwoIcon,
  "chat": ChatIcon,
  "chat-check": ChatCheckIcon,
  "chat-close": ChatCloseIcon,
  "chat-dots-horizontal": ChatDotsHorizontalIcon,
  "chat-exclamation": ChatExclamationIcon,
  "chat-info": ChatInfoIcon,
  "chat-question": ChatQuestionIcon,
  "check": CheckIcon,
  "check-circle": CheckCircleIcon,
  "chevron-down": ChevronDownIcon,
  "chevron-left": ChevronLeftIcon,
  "chevron-right": ChevronRightIcon,
  "chevron-up": ChevronUpIcon,
  "chrome": ChromeIcon,
  "clock": ClockIcon,
  "clock-variant-1": ClockVariantOneIcon,
  "clock-variant-2": ClockVariantTwoIcon,
  "close": CloseIcon,
  "cloud-download": CloudDownloadIcon,
  "cloud-download-variant-1": CloudDownloadVariantOneIcon,
  "code": CodeIcon,
  "code-variant-1": CodeVariantOneIcon,
  "copy": CopyIcon,
  "copy-variant-1": CopyVariantOneIcon,
  "discord": DiscordIcon,
  "discord-variant-1": DiscordVariantOneIcon,
  "docker": DockerIcon,
  "document": DocumentIcon,
  "document-variant-1": DocumentVariantOneIcon,
  "document-variant-2": DocumentVariantTwoIcon,
  "dots-horizontal": DotsHorizontalIcon,
  "dots-vertical": DotsVerticalIcon,
  "double-chevron-down": DoubleChevronDownIcon,
  "double-chevron-left": DoubleChevronLeftIcon,
  "double-chevron-right": DoubleChevronRightIcon,
  "double-chevron-up": DoubleChevronUpIcon,
  "download": DownloadIcon,
  "download-variant-1": DownloadVariantOneIcon,
  "download-variant-2": DownloadVariantTwoIcon,
  "edit-image": EditImageIcon,
  "exclamation-mark": ExclamationMarkIcon,
  "external-link": ExternalLinkIcon,
  "eye": EyeIcon,
  "eye-closed": EyeClosedIcon,
  "eye-slash": EyeSlashIcon,
  "eye-slash-variant-1": EyeSlashVariantOneIcon,
  "eye-variant-1": EyeVariantOneIcon,
  "facebook": FacebookIcon,
  "feed": FeedIcon,
  "filter": FilterIcon,
  "filter-variant-1": FilterVariantOneIcon,
  "firefox": FirefoxIcon,
  "folder": FolderIcon,
  "folder-variant-1": FolderVariantOneIcon,
  "folder-variant-2": FolderVariantTwoIcon,
  "git": GitIcon,
  "git-branch": GitBranchIcon,
  "git-branch-variant-1": GitBranchVariantOneIcon,
  "git-commit": GitCommitIcon,
  "git-commit-variant-1": GitCommitVariantOneIcon,
  "git-merge": GitMergeIcon,
  "git-merge-variant-1": GitMergeVariantOneIcon,
  "git-pull-request": GitPullRequestIcon,
  "git-pull-request-variant-1": GitPullRequestVariantOneIcon,
  "git-variant-1": GitVariantOneIcon,
  "github": GithubIcon,
  "gitlab": GitlabIcon,
  "gitlab-variant-1": GitlabVariantOneIcon,
  "google": GoogleIcon,
  "google-drive": GoogleDriveIcon,
  "google-meet": GoogleMeetIcon,
  "google-variant-1": GoogleVariantOneIcon,
  "half-heart": HalfHeartIcon,
  "half-heart-filled": HalfHeartFilledIcon,
  "half-star": HalfStarIcon,
  "half-star-filled": HalfStarFilledIcon,
  "heart": HeartIcon,
  "heart-filled": HeartFilledIcon,
  "home": HomeIcon,
  "home-variant-1": HomeVariantOneIcon,
  "image": ImageIcon,
  "image-check": ImageCheckIcon,
  "image-close": ImageCloseIcon,
  "image-minus": ImageMinusIcon,
  "image-plus": ImagePlusIcon,
  "image-variant-1": ImageVariantOneIcon,
  "info": InfoIcon,
  "instagram": InstagramIcon,
  "instagram-old": InstagramOldIcon,
  "internet-explorer": InternetExplorerIcon,
  "internet-globe": InternetGlobeIcon,
  "internet-globe-variant-1": InternetGlobeVariantOneIcon,
  "linkedin": LinkedinIcon,
  "linkedin-variant-1": LinkedinVariantOneIcon,
  "location": LocationIcon,
  "location-variant-1": LocationVariantOneIcon,
  "mail": MailIcon,
  "mail-open": MailOpenIcon,
  "mail-variant-1": MailVariantOneIcon,
  "menu": MenuIcon,
  "messenger": MessengerIcon,
  "meta": MetaIcon,
  "microsoft": MicrosoftIcon,
  "microsoft-edge": MicrosoftEdgeIcon,
  "microsoft-teams": MicrosoftTeamsIcon,
  "minus": MinusIcon,
  "minus-circle": MinusCircleIcon,
  "mobile-phone": MobilePhoneIcon,
  "mobile-phone-variant-1": MobilePhoneVariantOneIcon,
  "moon": MoonIcon,
  "moon-in-the-sea": MoonInTheSeaIcon,
  "moon-variant-1": MoonVariantOneIcon,
  "npm": NpmIcon,
  "npm-variant-1": NpmVariantOneIcon,
  "opera": OperaIcon,
  "pause": PauseIcon,
  "pencil": PencilIcon,
  "pencil-variant-1": PencilVariantOneIcon,
  "pencil-variant-2": PencilVariantTwoIcon,
  "phone": PhoneIcon,
  "phone-variant-1": PhoneVariantOneIcon,
  "pinterest": PinterestIcon,
  "pinterest-variant-1": PinterestVariantOneIcon,
  "play": PlayIcon,
  "play-pause": PlayPauseIcon,
  "plus": PlusIcon,
  "plus-circle": PlusCircleIcon,
  "plus-minus": PlusMinusIcon,
  "profile": ProfileIcon,
  "profile-variant-1": ProfileVariantOneIcon,
  "question-mark": QuestionMarkIcon,
  "reddit": RedditIcon,
  "refresh": RefreshIcon,
  "refresh-variant-1": RefreshVariantOneIcon,
  "safari": SafariIcon,
  "save": SaveIcon,
  "save-variant-1": SaveVariantOneIcon,
  "save-variant-2": SaveVariantTwoIcon,
  "search": SearchIcon,
  "send": SendIcon,
  "send-variant-1": SendVariantOneIcon,
  "send-variant-2": SendVariantTwoIcon,
  "send-variant-3": SendVariantThreeIcon,
  "send-variant-4": SendVariantFourIcon,
  "settings": SettingsIcon,
  "settings-variant-1": SettingsVariantOneIcon,
  "signal": SignalIcon,
  "skype": SkypeIcon,
  "slack": SlackIcon,
  "snapchat": SnapchatIcon,
  "snapchat-variant-1": SnapchatVariantOneIcon,
  "stackoverflow": StackoverflowIcon,
  "star": StarIcon,
  "star-filled": StarFilledIcon,
  "sun": SunIcon,
  "sun-in-the-sea": SunInTheSeaIcon,
  "sun-variant-1": SunVariantOneIcon,
  "telegram": TelegramIcon,
  "telegram-variant-1": TelegramVariantOneIcon,
  "terminal": TerminalIcon,
  "terminal-variant-1": TerminalVariantOneIcon,
  "terminal-variant-2": TerminalVariantTwoIcon,
  "tiktok": TiktokIcon,
  "trash": TrashIcon,
  "trash-variant-1": TrashVariantOneIcon,
  "twitch": TwitchIcon,
  "twitter": TwitterIcon,
  "upload": UploadIcon,
  "upload-variant-1": UploadVariantOneIcon,
  "upload-variant-2": UploadVariantTwoIcon,
  "vercel": VercelIcon,
  "vercel-variant-1": VercelVariantOneIcon,
  "warning-circle": WarningCircleIcon,
  "warning-triangle": WarningTriangleIcon,
  "whatsapp": WhatsappIcon,
  "wifi": WifiIcon,
  "wifi-exclamation": WifiExclamationIcon,
  "wifi-low": WifiLowIcon,
  "wifi-medium": WifiMediumIcon,
  "wifi-slash": WifiSlashIcon,
  "wifi-very-low": WifiVeryLowIcon,
  "windows": WindowsIcon,
  "youtube": YoutubeIcon,
  "youtube-variant-1": YoutubeVariantOneIcon,
};

export { iconRegistry };
